config/routes.rb
Rails.application.routes.draw do
  root "tasks#index"
  resources :tasks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
    before_save :ensure_completed_value

    private

    def ensure_completed_value
        self.completed = false if completed.nil?
        max_position = Task.maximum(:position) || 0
        self.position = max_position + 1
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    def index
        @tasks = Task.all
        @task = Task.new
        @done_tasks = Task.where(completed: true).order(:position)
        @doing_tasks = Task.where(completed: false).order(:position)
    end

    def edit
        @task = Task.find(params[:id])
    end

    def update
        @task = Task.find(params[:id])
        @task.update(completed: params[:completed])

        render json: { message: "Success" }
    end

    def destroy
        @task = Task.find(params[:id])
        @task.destroy
        redirect_to tasks_path, notice: "Task was successfully deleted."
    end

    def create
        @task = Task.new(task_params)

        respond_to do |format|
            if @task.save
                format.html { redirect_to tasks_url, notice: "Task was successfully created." }
            else
                format.html { render :new, status: :unproccessable_entity }
            end
        end
    end

    private

    def task_params
        params.require(:task).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Task App" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex flex-col">
      <%= yield %>
    </main>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: task, class: "mb-7") do |form| %>
    <div class="mb-5">
        <%= form.text_field :name, placeholder: "Add new task", class: "inline-block w-96 px-3 py-2 mt-2 shadow rounded-md border border-gray-200 outline-none" %>
        <%= form.submit "Save", class: "btn py-2 ml-2 bg-blue-600 text-white" %>
    </div>
<% end %>

app/views/tasks/_task.html.erb
<li data-id="<%= task.id %>" class="item block mb-2" draggable="true" data-tasks-target="task" data-action="dragstart->tasks#startDrag dragover->tasks#allowDrop drop->tasks#drop">
    <%= task.name %>
    <%= link_to "Edit", edit_task_path(task), data: { turbo_frame: dom_id(task) }, class:"btn bg-gray-100" %>
    <div class="inline-block ml-2">
        <%= button_to "Delete", task_path(task), method: :delete, class: "btn bg-red-100" %>
    </div>
</li>

app/views/tasks/_tasklist.html.erb
<div id="tasklist">
    <h1 class="font-bold text-lg mb-7">Tasks</h1>
        <div class="flex">
            <div>
                <h1 class="font-bold text-lg mb-7 ml-7">Doing</h1>
                <ul class="px-5 size-[500px]" data-controller="tasks" data-tasks-target="doingList">
                    <% @doing_tasks.each do |task| %>
                        <%= render task %>
                    <% end %>
                </ul>
            </div>
            <div>
                <h1 class="font-bold text-lg mb-7 ml-7">Done</h1>
                <ul class="px-5 size-[500px]" data-controller="tasks" data-tasks-target="doneList">
                    <% @done_tasks.each do |task| %>
                        <%= render task %>
                    <% end %>
                </ul>
            </div>
        </div>
</div>

app/views/tasks/edit.html.erb
<div>
  <h1 class="font-bold text-2xl mb-3">Editing Task</h1>

  <div id="<%= dom_id @task %>">
    <%= render "form", task: @task %>
    <%= link_to "go back", tasks_path, class: "btn mb-3 bg-gray-100" %>
  </div>
</div>

app/views/tasks/index.html.erb
<% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 m-5 text-green-500 font-medium rounded-lg inline-block" id="notice">
        <%= notice %>
    </p>
<% end %>

<h1 class="font-bold text-2xl">Task Manager</h1>

<div class="mt-4">
    <%= render "form", task:@task %>
</div>

<%= render "tasklist" %>